[package]
name = "doglang"
version = "0.1.0"
authors = ["Erik Hyrkas <erik.hyrkas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "110.0.0"
clap = "2.33.3"
# structopt = "0.3"